BEHIIV_TOKEN: ENC[AES256_GCM,data:dXIty4kkkJgMqn6oRvO7x0KOV0u/YUAG2kuo1Al4UjP0/+wnfpprLO+1sdwFm6FSZqAIZDvsoUyYypkxfAz7CA==,iv:5NqgYxeeYbRXRg5lwdM/LZ5WQpd1mt0CtXcZxHdVsYU=,tag:30EqYiflXCsCrdIKDlk2ZQ==,type:str]
BEHIIV_PUB_KEY: ENC[AES256_GCM,data:XovyCeq9FqOoOdAZcUdykE1CsFejjK2T7ROuGcTcTqRR/bUqvQQVaw==,iv:+I+NwMRn3tKggxAyvNTndKheOHElATdp9ogCWd2gjGw=,tag:lrDYNJtjuA4v7BG5Ql6kaw==,type:str]
RESEND_API_KEY: ENC[AES256_GCM,data:5St/a6V9hJZPa0urQ6BxacR9pQmVnmwGpXIW6o2/V8WSM4qA,iv:OW7JeQXNlaOqIc9opG0Ijrvf9xtXxyntcD0y+a52SRk=,tag:UhjMIeGxSJdNbpGvsJdTyw==,type:str]
CONTACT_TO_EMAIL: ENC[AES256_GCM,data:bex5kV2k/0zgUTbXaYBBo2RDnMxYXwc=,iv:JRyBhbYJv19ihbDI+zG6ojwvZQPQit2fmZ6NMOoxWzw=,tag:w96HNBxP9vSCX6vhepyhYg==,type:str]
CONTACT_FROM_EMAIL: ENC[AES256_GCM,data:wVENgndfGOMhtEkBoljYXxNoruuU73TcVw==,iv:Jkp30M2Sq7McpSz0dALxX/oHnvXoymvJXnPWlUVRDWM=,tag:ocBdDQyxTZNYdjmdxZB+Ow==,type:str]
IBAN: ENC[AES256_GCM,data:hbamaFKQYZJTCKvePpLI+23ntQ==,iv:P1aMpv+nIjoR9/SaN5/t5cbcRB/phD4PcdeO04d9ZAk=,tag:W+TsYubZKqYJ9NJTz/c8yA==,type:str]
BIC: ENC[AES256_GCM,data:ugvvjqVNmmSpVnw=,iv:EZ2t48xah5kX2dJo3aDJiEQe8W3dPH3OBZctHQR4GE8=,tag:399AFfiIckPwOs1srYH0cg==,type:str]
STRAPI_URL: ENC[AES256_GCM,data:zcfAixfpoSuQyPq45brdTKHNkUgtCN4mD0ZO5C8=,iv:WVsZKUUr3LQjf0SwYK7ukDQzcZS+/R6X5pszDZRZUE4=,tag:eKp+lCGLkam2ar2NGfetHg==,type:str]
STRAPI_DOMAIN: ENC[AES256_GCM,data:WFcC6NGqb3gtYDwQ8VQwfcwuFO9K,iv:zuYKyqUvitLoaHo6k7AzaBVN7RNw+VHuvvz+DdNQx+U=,tag:QrvjrcMlV9RrSDCRiAO+dw==,type:str]
STRAPI_KEY: ENC[AES256_GCM,data:jtkWbDeu0Bs130rZnd2XmjhSjEuKqXSFCcyjy8yVKSKnWHS6SaWGBQg0Wwef4t4uZEDr7rcr3my0PT51x77kiyIfIteXhUH8OArjTFSRPTI+ldMsWPtZMHVZjAEvnR36MsNP65CenfU4pLY+LuAD2PuwkYiUJDdHvhF5iKFFvEJvDEURr7F1mTWHp4gu+tbWg/qPvQguXqOUu+r7AphEkDRcCKQRdsLIJRa0/wMyeosBnpkXfX9kx2txpwS7HCxyUl/iS8fyDfeIi4L9VECOEfAEh8iOGm1vdSIprtZObZ9yx4UPAVnt07Jq67zaD2lobDj1KdhPKqNyTbSCl3zEFQ==,iv:ZL/B68BiyKBaaPIKMQrexONL3ZnM8E+FL9GaNG9IHhU=,tag:/RCosqZ7nXI+5FTB3cLiwg==,type:str]
sops:
    age:
        - recipient: age18czeejgx4sqes9lulh02af08z39u98lsm7dcuprk2y5yag43uegskuuhff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSd0dHbk1JbGt2SENzOVpr
            akVRM3VrTXR4U1NadnhtK3pLa055aFNSYlNJCjFwNkpxWkNxYkxvczNZZVA1NFVZ
            c0VnS05kci80ZlV5VmQxa241T3N4WE0KLS0tIFkwTmNHeDY3dGlBb1FWb0pSRGky
            L1FraFM3RjViSFh0VEhmTmlidEtPTlkK99wU7n2PY7achDlKkEN4Fd+cmsM33GMb
            aVf9dpQToD0CWglyXwykREjDONmcvm3W00VkGL/adaYqTx+MVrILyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16z3ewnx22h4j4qxmaj43yysag8a3gnxs46mm9p0s92lcykwr952syq8365
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbTlzdHQ1SUpLRytDbTVv
            bmV6SkhzZC93ZnNZZ0VScU9DM2pPMHY0OFIwCkJzVmd0NVAyT3dPbFVCdlNabDFR
            R0s1L0ZHZWlaM1JaNzJPNldyMzkrT28KLS0tIFpKOVN1N2wrMXRZNmxzOWNsdEE1
            NTdScDM1ZFEyV0hkZE1VT243dUZZbncKzYW58C7pS7E4RvnTLWBIK3oJ0zeFuj48
            WRqXvLrabPfeMcepyzzR0o4A1wtlBlmtp/B3dhkSKcLHaNTfYttXUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k349xhtvfswn44wprj03pnlxafry0y2uyl23hy3e8zpxavjaysmqg62q9y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUkZnVHNsNkVoVGVsTE9R
            SW5zZlplaHlWOU14SjZKOCt2Q3c1MGR5Zm5RCmYxWVhvS2hobC8xQ2FocDNSU25E
            aEp0bHBHME9BQzY5c2I2RnFUUU9INTAKLS0tIEQvMkVjdmFabklHbXBtd1dvZzVZ
            dERvdG15U05OY1lnczg0MUJzVVVvQ2MKq4h2ZNLL1H0NoC5Usxjub4XrLG56MBeD
            RpHyFOd1x55FUkwnZ66bh8X17ez0kOCAUGJoYtvo/zu1WWpbZggKQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mzmws9mpksrk7chzxwrg570x77gjdsspswpzuta9q38fy7a57f5q0ks5x4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWC9HYi9PR0NjUGpRbGN3
            UThWK245YVRWazB2OWJBcHYzN2lnUm1OY3hZCkppYXZmMzBCaFhaa2g4MXNEZ0R2
            bS9EeWRTZlV0clVaSWtkOG83cHRaY2cKLS0tIEFBdlA1TnNFb29CaDcyVXJnclFB
            bnpPL01lZnlWNFhPT0tIZFQ1QUpES3cK+crZV9W2ZYg9w1XcqDZjuYVE3Q4qsy0j
            whGTJy4yTHndxh/Nu37j+7Tr6kGjyz0jRjFB+EHveawK+gFndVLT2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15z0l8mlxuet0n9s70c3fr4n9t9upt9yaxnfmxjz28h4j3c7yravqekrd04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVVI4NVltdTQ5S0NPaEpX
            cndmM0hVV1BLTEhJZGxmSFgxMzNIQlhVOGh3CjNEUEYxOVJOM3ljazBNckVFYWZE
            M2NhdjlGVlhBSXZnblgrcVFsNEVUUEUKLS0tIEdqZmFSZFNVRGJrWEo3RUpSZ3Uz
            QktOb2Vxa2diUGNnV2FXeHRpRHNwamsK03W+VFYRobTpALoTHdFkwdL9ftVxk0Zv
            5Je3ome9w+h4HEVuk4Vxay42OwpMy/MDP5zZTvxP6JVW+kKyTSxoOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T18:00:47Z"
    mac: ENC[AES256_GCM,data:aRqxsXKqSdkJKX/Rs5i73M0jAHoNkrgmcc5eCiYDkyxwpG7mjh1/ThEoCsVCdSJyoxco+6JLSr0ILMbiq2CXrS/fJNuo55ZRvW8Hr6TSQdlYG4/PtTrIH5kRMR+zQPj3PpQq5lALU4/l52LEfJyuyi5In/OYqf969rpyv0F6aEU=,iv:Q26V/6BdRSNFFRlOXJvvEeT7qd2K9nxzkltzpojKi7M=,tag:8aj8uZhKT8qZqD5y0QHqFw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
