BEHIIV_TOKEN: ENC[AES256_GCM,data:dXIty4kkkJgMqn6oRvO7x0KOV0u/YUAG2kuo1Al4UjP0/+wnfpprLO+1sdwFm6FSZqAIZDvsoUyYypkxfAz7CA==,iv:5NqgYxeeYbRXRg5lwdM/LZ5WQpd1mt0CtXcZxHdVsYU=,tag:30EqYiflXCsCrdIKDlk2ZQ==,type:str]
BEHIIV_PUB_KEY: ENC[AES256_GCM,data:XovyCeq9FqOoOdAZcUdykE1CsFejjK2T7ROuGcTcTqRR/bUqvQQVaw==,iv:+I+NwMRn3tKggxAyvNTndKheOHElATdp9ogCWd2gjGw=,tag:lrDYNJtjuA4v7BG5Ql6kaw==,type:str]
RESEND_API_KEY: ENC[AES256_GCM,data:5St/a6V9hJZPa0urQ6BxacR9pQmVnmwGpXIW6o2/V8WSM4qA,iv:OW7JeQXNlaOqIc9opG0Ijrvf9xtXxyntcD0y+a52SRk=,tag:UhjMIeGxSJdNbpGvsJdTyw==,type:str]
CONTACT_TO_EMAIL: ENC[AES256_GCM,data:bex5kV2k/0zgUTbXaYBBo2RDnMxYXwc=,iv:JRyBhbYJv19ihbDI+zG6ojwvZQPQit2fmZ6NMOoxWzw=,tag:w96HNBxP9vSCX6vhepyhYg==,type:str]
CONTACT_FROM_EMAIL: ENC[AES256_GCM,data:wVENgndfGOMhtEkBoljYXxNoruuU73TcVw==,iv:Jkp30M2Sq7McpSz0dALxX/oHnvXoymvJXnPWlUVRDWM=,tag:ocBdDQyxTZNYdjmdxZB+Ow==,type:str]
IBAN: ENC[AES256_GCM,data:hbamaFKQYZJTCKvePpLI+23ntQ==,iv:P1aMpv+nIjoR9/SaN5/t5cbcRB/phD4PcdeO04d9ZAk=,tag:W+TsYubZKqYJ9NJTz/c8yA==,type:str]
BIC: ENC[AES256_GCM,data:ugvvjqVNmmSpVnw=,iv:EZ2t48xah5kX2dJo3aDJiEQe8W3dPH3OBZctHQR4GE8=,tag:399AFfiIckPwOs1srYH0cg==,type:str]
STRAPI_URL: ENC[AES256_GCM,data:zcfAixfpoSuQyPq45brdTKHNkUgtCN4mD0ZO5C8=,iv:WVsZKUUr3LQjf0SwYK7ukDQzcZS+/R6X5pszDZRZUE4=,tag:eKp+lCGLkam2ar2NGfetHg==,type:str]
STRAPI_DOMAIN: ENC[AES256_GCM,data:WFcC6NGqb3gtYDwQ8VQwfcwuFO9K,iv:zuYKyqUvitLoaHo6k7AzaBVN7RNw+VHuvvz+DdNQx+U=,tag:QrvjrcMlV9RrSDCRiAO+dw==,type:str]
STRAPI_KEY: ENC[AES256_GCM,data:jtkWbDeu0Bs130rZnd2XmjhSjEuKqXSFCcyjy8yVKSKnWHS6SaWGBQg0Wwef4t4uZEDr7rcr3my0PT51x77kiyIfIteXhUH8OArjTFSRPTI+ldMsWPtZMHVZjAEvnR36MsNP65CenfU4pLY+LuAD2PuwkYiUJDdHvhF5iKFFvEJvDEURr7F1mTWHp4gu+tbWg/qPvQguXqOUu+r7AphEkDRcCKQRdsLIJRa0/wMyeosBnpkXfX9kx2txpwS7HCxyUl/iS8fyDfeIi4L9VECOEfAEh8iOGm1vdSIprtZObZ9yx4UPAVnt07Jq67zaD2lobDj1KdhPKqNyTbSCl3zEFQ==,iv:ZL/B68BiyKBaaPIKMQrexONL3ZnM8E+FL9GaNG9IHhU=,tag:/RCosqZ7nXI+5FTB3cLiwg==,type:str]
sops:
    age:
        - recipient: age18czeejgx4sqes9lulh02af08z39u98lsm7dcuprk2y5yag43uegskuuhff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVN0RWc0w2NFh2WkZaR1I0
            MDFXU2s4ZnRoZitkTWNJVzVOb3FaQ1BKb0FZCmU2aWFpcmV3VHIwN2tiQ2VzMFBK
            NCswV0Zrc1dlWHZ0UkwzZVIzdC9mb3MKLS0tIFhnOWRGRlBPNUJ0akFuSHd0MVBv
            am9QWmRIblRyaURuT0JYT1VPalNRSE0KmmXQgR/kXGfHTe1WWzpYvW4+QUgJLMl5
            EUy5QlAQB+rSwNdiXCYtyzUzh7RfYKuHx7f6yyBH9US9D3JjaBUDfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16z3ewnx22h4j4qxmaj43yysag8a3gnxs46mm9p0s92lcykwr952syq8365
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVnlab291dEVTSWtsM2xk
            bHJYOENKckxTK2MrcmlUT1ZFcXh0WFNteW1rClMzYXI4K21kMnZLb3czdjhwaW1O
            d3Zka2lScW45amk3S0h4VTRUcXdINlEKLS0tIFF3U2NFaVM3ZDdKR2hYdFEyOUh2
            QWVPd3VHeHVKbW1aZy9qdjdzQWUzSjgKkMBS0b7B5YPzF+UIVoRfDhXSSLNrv651
            owDAIR64oZKkz+7D+EKpv4G5L8ceE5puEc0l38uzZDGgG98GdUbn/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k349xhtvfswn44wprj03pnlxafry0y2uyl23hy3e8zpxavjaysmqg62q9y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByd3FKdmx4SVUycDF5QWNX
            aTBIbHhMU3ppMXkrUy9EM2VRUjdiN3BCdEdnCjF3N3JxSUJNTDY4NTdxRnkzNHpF
            Y25Zc2lzU25vTm52MVFIZllsYWdsUFkKLS0tIFlqeldxTkljRDBvOVBhVnBMZC9w
            dVBKM0JUVWN2c2Q5ME5rQ0pOREJXYU0KKjxODT6f75g28OdWgtCRB4/+Q/zO+G0Y
            k16vKGPyA8nHfjtuVLLCiXWA2tJ0U/za1rl3/BJM93pM5rgrhQhyhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T18:00:47Z"
    mac: ENC[AES256_GCM,data:aRqxsXKqSdkJKX/Rs5i73M0jAHoNkrgmcc5eCiYDkyxwpG7mjh1/ThEoCsVCdSJyoxco+6JLSr0ILMbiq2CXrS/fJNuo55ZRvW8Hr6TSQdlYG4/PtTrIH5kRMR+zQPj3PpQq5lALU4/l52LEfJyuyi5In/OYqf969rpyv0F6aEU=,iv:Q26V/6BdRSNFFRlOXJvvEeT7qd2K9nxzkltzpojKi7M=,tag:8aj8uZhKT8qZqD5y0QHqFw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
