import React from 'react'
import type { Metadata } from 'next'
import './globals.css'
import Footer from '@/components/shared/Footer'
import { Lato } from 'next/font/google';

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Distribute Aid',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
