import React from "react";
import type { Metadata } from "next";

import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";

import { Yantramanav, Roboto, Permanent_Marker } from "next/font/google";
import "../stylesheets/main.css";

import NavBar from "../components/nav/navBar";
import Footer from "@/components/ui/Footer";
import GetInvolved from "@/components/ui/GetInvolved";

const yantramanav = Yantramanav({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-yantramanav",
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
});
const permanentMarker = Permanent_Marker({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-permanent-marker",
});

export const metadata: Metadata = {
  title: "Distribute Aid",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${yantramanav.variable} ${roboto.variable} ${permanentMarker.variable}`}
      >
        <Theme accentColor="blue">
          <NavBar />
          <div className="pt-20">{children}</div>
          <GetInvolved />
          <Footer />
        </Theme>
      </body>
    </html>
  );
}
